AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  GitHubOwner:
    Type: String
    Default: superluminar-io
  RepositoryName:
    Type: String
    Default: code-pipeline-example
  BuildSpecFileName:
    Type: String
    Description: The name of the buildspec to use from the github repo
    Default: pr-test-buildspec.yml

Resources:
  BuilderRole:
    Description: The IAM Role used to run the codebuild job.  Customise this if you need add extra permissions.
    Type: AWS::IAM::Role
    Properties:
      RoleName: BuilderRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  Policy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref BuilderRole
      PolicyName: "logs"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${BuildProject}"
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${BuildProject}:*"

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-build"
      ServiceRole: !GetAtt BuilderRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1
      Source:
        Auth:
          Type: OAUTH
          Resource: arn:aws:secretsmanager:eu-west-1:190962764617:secret:/aws-ci-examples/github-token-dObryX
        Location: !Sub "https://github.com/${GitHubOwner}/${RepositoryName}"
        ReportBuildStatus: true
        Type: GITHUB
        BuildSpec: !Ref BuildSpecFileName
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: "PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED"
